### ISSUE TITLE
Reach out to JHU and see if we can be a part of their scraping operation

### ISSUE THREAD

**Issue by Dilcia19** [biglocalnews/covid-world-scraper#79]
The best course of action would just be to build on top of what they already have instead of running our own operation if possible, however, they've been a little hard to track down and it may be necessary for us to put out our own data in the short-term.

**Comment by Dilcia19** [comment]
I reached out to: dougdonovan@jhu.edu (contact for media), 
wsecommunications@jhu.edu (Whiting School of Engineering), and l.gardner@jhu.edu (Lauren Gardner​
ASSOCIATE PROFESSOR OF CIVIL ENGINEERING
CSSE CO-DIRECTOR)

Not sure if we reached out to any of these emails/people initially.
I will follow up within a few days if I don't hear back.

**Comment by zstumgoren** [comment]
@Dilcia19 nice! I initially reached out to doug donovan, who i *think* forwarded me on to Seth Zonies. He's the person who notified me about the new licensing terms for COVID data. Subsequent attempts to contact him have gone unanswered, but might be worth another try. I'll pass along contact details in a private channel.

**Comment by Dilcia19** [comment]
I sent an email to Seth Zonies as well. Waiting to hear back from any of those emails, we will see how it goes.

**Comment by Dilcia19** [comment]
They never responded.
